const candidateData = [
    {
      title: 'Front End Dev',
      name: 'John Doe',
      image: '',
      deployedLink: '/',
      githubLink: '/',
      isCommitted: false,
      isSubmitted: false,
      isPlaced: false,
      jobPlaced: null,
      jobsFavorited: [],
      jobsCommitted: [],
      currentRecruiters: {}
    },
    {
      title: 'Back End Dev',
      name: 'Jane Doe',
      image: '',
      deployedLink: '/',
      githubLink: '/',
      isCommitted: true,
      isSubmitted: false,
      isPlaced: false,
      jobPlaced: null,
      jobsFavorited: [],
      jobsCommitted: [],
      currentRecruiters: {}
    },
    {
      title: 'Full Stack Developer',
      name: 'Michael Smith',
      image: '',
      deployedLink: '/',
      githubLink: '/',
      isCommitted: false,
      isSubmitted: false,
      isPlaced: false,
      jobPlaced: null,
      jobsFavorited: [],
      jobsCommitted: [],
      currentRecruiters: {}
    },
    {
      title: 'UI/UX Designer',
      name: 'Emily Johnson',
      image: '',
      deployedLink: '/',
      githubLink: '/',
      isCommitted: false,
      isSubmitted: false,
      isPlaced: false,
      jobPlaced: null,
      jobsFavorited: [],
      jobsCommitted: [],
      currentRecruiters: {}
    },
    {
      title: 'Data Scientist',
      name: 'David Anderson',
      image: '',
      deployedLink: '/',
      githubLink: '/',
      isCommitted: true,
      isSubmitted: true,
      isPlaced: false,
      jobPlaced: null,
      jobsFavorited: [],
      jobsCommitted: [],
      currentRecruiters: {}
    },
    {
      title: 'Software Engineer',
      name: 'Jennifer Smith',
      image: '',
      deployedLink: '/',
      githubLink: '/',
      isCommitted: false,
      isSubmitted: false,
      isPlaced: false,
      jobPlaced: null,
      jobsFavorited: [],
      jobsCommitted: [],
      currentRecruiters: {}
    },
    {
      title: 'Network Administrator',
      name: 'Mark Thompson',
      image: '',
      deployedLink: '/',
      githubLink: '/',
      isCommitted: false,
      isSubmitted: false,
      isPlaced: false,
      jobPlaced: null,
      jobsFavorited: [],
      jobsCommitted: [],
      currentRecruiters: {}
    },
    {
      title: 'Digital Marketing Specialist',
      name: 'Sarah Williams',
      image: '',
      deployedLink: '/',
      githubLink: '/',
      isCommitted: true,
      isSubmitted: false,
      isPlaced: false,
      jobPlaced: null,
      jobsFavorited: [],
      jobsCommitted: [],
      currentRecruiters: {}
    },
    {
      title: 'Product Manager',
      name: 'Alex Rodriguez',
      image: '',
      deployedLink: '/',
      githubLink: '/',
      isCommitted: false,
      isSubmitted: false,
      isPlaced: false,
      jobPlaced: null,
      jobsFavorited: [],
      jobsCommitted: [],
      currentRecruiters: {}
    },
    {
      title: 'Cybersecurity Analyst',
      name: 'Laura Davis',
      image: '',
      deployedLink: '/',
      githubLink: '/',
      isCommitted: true,
      isSubmitted: true,
      isPlaced: true,
      jobPlaced: null,
      jobsFavorited: [],
      jobsCommitted: [],
      currentRecruiters: {}
    }
    // Add more candidates as needed
  ];
  
  export default candidateData;
  